# Generated by Django 5.2.6 on 2025-12-29 22:50

import Bapp.models
import django.db.models.deletion
import pyotp
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnoncesMembersView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/missidhe_bourou_img')),
                ('extra_links', models.URLField(blank=True, null=True)),
                ('published_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'annonces_members_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CotisationAnnuelleView_Save',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_cotisation', models.DateTimeField()),
            ],
            options={
                'db_table': 'cotisation_annuelle_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CotisationOccasionnelleView_save',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif_cotisation', models.TextField()),
                ('date_cotisation', models.DateTimeField()),
            ],
            options={
                'db_table': 'cotisation_occasionnelle_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepensesView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('montant_depense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif_depense', models.TextField()),
                ('date_depense', models.DateTimeField()),
            ],
            options={
                'db_table': 'depenses_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DonsView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('montant_don', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif_don', models.TextField()),
                ('date_don', models.DateTimeField()),
            ],
            options={
                'db_table': 'dons_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MissidehBourouMembersView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('identifiant', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'missideh_bourou_members_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusMemberAnnualParticipation_save',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prenoms', models.TextField()),
                ('quartier', models.TextField()),
                ('statut_par_annee', models.JSONField()),
            ],
            options={
                'verbose_name': 'Participation annuelle (vue)',
                'verbose_name_plural': 'Participations annuelles (vue)',
                'db_table': 'status_member_annual_participation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotauxView_save',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('montant_cotisationannuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_cotisationoccasionnelle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_dons', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_depenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_annuel', models.CharField(blank=True, max_length=64, null=True)),
                ('type_occasionnelle', models.CharField(blank=True, max_length=64, null=True)),
                ('type_dons', models.CharField(blank=True, max_length=64, null=True)),
                ('type_depenses', models.CharField(blank=True, max_length=64, null=True)),
                ('aujourdhui', models.DateTimeField()),
            ],
            options={
                'db_table': 'totaux_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AmountContributionYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('amount_to_paid_pro_year', models.FloatField()),
            ],
            options={
                'db_table': 'amount_contribution_yearly',
            },
        ),
        migrations.CreateModel(
            name='DashboardModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('url_name', models.CharField(max_length=100)),
                ('required_role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('PRESIDENT', 'Président'), ('VICE_PRESIDENT', 'Vice-président'), ('PORTE_PAROLE', 'Porte-parole'), ('MODERATOR', 'Modérateur'), ('EDITOR', 'Éditeur'), ('USER', 'Membre'), ('SECRETOR', 'Sécréteur'), ('SECOND_SECRETOR', 'Second sécréteur')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dashboard_module',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EditorialCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/missidhe_bourou_img')),
                ('extra_links', models.URLField(blank=True, null=True)),
                ('author', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'editorial_community',
            },
        ),
        migrations.CreateModel(
            name='EvenementOccasionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
                ('date_event', models.DateField()),
            ],
            options={
                'db_table': 'evenement_occasionnelle',
            },
        ),
        migrations.CreateModel(
            name='BtestCustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('prenoms', models.CharField(max_length=120)),
                ('quartier', models.CharField(default='Kowli', max_length=60)),
                ('identifiant', models.CharField(blank=True, max_length=20, unique=True)),
                ('pays', models.CharField(max_length=30)),
                ('city', models.CharField(default='Labé', max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=Bapp.models.get_profile_image_path)),
                ('otp_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('otp_enabled', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verification_token', models.UUIDField(blank=True, null=True, unique=True)),
                ('email_verification_expiration', models.DateTimeField(blank=True, default=Bapp.models.default_email_verification_expiration, null=True)),
                ('password_changed', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_moderator', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('PRESIDENT', 'Président'), ('VICE_PRESIDENT', 'Vice-président'), ('PORTE_PAROLE', 'Porte-parole'), ('MODERATOR', 'Modérateur'), ('EDITOR', 'Éditeur'), ('USER', 'Membre'), ('SECRETOR', 'Sécréteur'), ('SECOND_SECRETOR', 'Second sécréteur')], default='USER', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_user', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'btest_custom_user',
                'permissions': [('manager_adminstrators', 'Can manage administrators'), ('manage_users', 'Can manage users'), ('manage_articles', 'Can manage articles'), ('manager_cotisations', 'Can manage cotisations'), ('manager_depenses', 'Can manage depenses')],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorSettingsTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('telegram_linked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twofa_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'two_factor_settings_telegram',
            },
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_code', models.CharField(max_length=8)),
                ('channel', models.CharField(choices=[('email', 'email'), ('whatsapp', 'whatsapp'), ('telegram', 'telegram')], default='email', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_auth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'two_factor_auth',
            },
        ),
        migrations.CreateModel(
            name='TelegramOTP2FA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(default=pyotp.random_base32, max_length=32)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResetPasswordToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiration', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PDFManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('file', models.FileField(upload_to='pdfs/%Y/%m/%d/', verbose_name='Fichier PDF')),
                ('document_type', models.CharField(choices=[('USER_LIST', 'Liste des utilisateurs'), ('ANNUAL_COTISATION', 'Cotisation annuelle'), ('OCCASIONNAL_COTISATION', 'Cotisation occasionnelle'), ('DONS', 'Rapport des ventes'), ('DEPENSES', 'Dépenses effectuées'), ('BILAN_CAISSE', 'Bilan financier'), ('INFO', 'Annonces ')], max_length=100, verbose_name='Type de document')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_pdfs', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'PDF généré',
                'verbose_name_plural': 'PDFs générés',
                'db_table': 'pdf_manager',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipationOccasionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_participation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif_participation', models.TextField()),
                ('year', models.PositiveIntegerField(default=Bapp.models.current_year)),
                ('date_participation', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_participation_occasionnelle', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('montant_don', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif_don', models.TextField()),
                ('date_don', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_dons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dons',
            },
        ),
        migrations.CreateModel(
            name='CotisationOccasionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_cotisation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_cotisation', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('event_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='motifs_cotisations', to='Bapp.evenementoccasionnelle')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_cotisation_occasionnelle', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'evenement_cotisation_occasionnelle',
            },
        ),
        migrations.CreateModel(
            name='AddDepenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_depense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif_depense', models.TextField()),
                ('date_depense', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'depenses',
            },
        ),
        migrations.CreateModel(
            name='ParticipationAnnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_participation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_participation', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='Bapp.amountcontributionyear')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_participation_annuel', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'participation_annuel',
                'constraints': [models.UniqueConstraint(fields=('participant', 'year'), name='unique_participation_annuel')],
            },
        ),
    ]
