# Generated by Django 5.2.1 on 2025-06-17 00:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTestCustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('prenoms', models.CharField(max_length=60)),
                ('quartier', models.CharField(default='Kowli', max_length=60)),
                ('identifiant', models.CharField(blank=True, max_length=20, unique=True)),
                ('pays', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('email_verification_token', models.UUIDField(blank=True, null=True, unique=True)),
                ('email_verification_expiration', models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 18, 0, 2, 7, 435738, tzinfo=datetime.timezone.utc), null=True)),
                ('password_changed', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_moderator', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('MODERATOR', 'Modérateur'), ('EDITOR', 'Éditeur'), ('USER', 'Utilisateur normal')], default='USER', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipationAnnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_participation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_participation', models.DateField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
