# Generated by Django 5.2.6 on 2025-12-29 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorialcommunity',
            name='author',
        ),
        migrations.AddField(
            model_name='amountcontributionyear',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_amount_contribution_year', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='editorialcommunity',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_editorial_community', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evenementoccasionnelle',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_evenement_occasionnelle', to=settings.AUTH_USER_MODEL),
        ),
    ]
