# Generated by Django 5.2.1 on 2025-06-17 00:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btestcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 18, 0, 13, 3, 456663, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
