# Generated by Django 5.2.6 on 2026-01-02 04:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0002_remove_editorialcommunity_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotisationAnnuelleView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_cotisation', models.DateTimeField()),
            ],
            options={
                'db_table': 'cotisation_annuelle_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CotisationOccasionnelleView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prenom', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif_cotisation', models.TextField()),
                ('date_cotisation', models.DateTimeField()),
            ],
            options={
                'db_table': 'cotisation_occasionnelle_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusMemberAnnualParticipation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prenoms', models.TextField()),
                ('quartier', models.TextField()),
                ('statut_par_annee', models.JSONField()),
            ],
            options={
                'verbose_name': 'Participation annuelle (vue)',
                'verbose_name_plural': 'Participations annuelles (vue)',
                'db_table': 'status_member_annual_participation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotauxView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('montant_cotisationannuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_cotisationoccasionnelle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_dons', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_depenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_annuel', models.CharField(blank=True, max_length=64, null=True)),
                ('type_occasionnelle', models.CharField(blank=True, max_length=64, null=True)),
                ('type_dons', models.CharField(blank=True, max_length=64, null=True)),
                ('type_depenses', models.CharField(blank=True, max_length=64, null=True)),
                ('aujourdhui', models.DateTimeField()),
            ],
            options={
                'db_table': 'totaux_view',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CotisationAnnuelleView_Save',
        ),
        migrations.DeleteModel(
            name='CotisationOccasionnelleView_save',
        ),
        migrations.DeleteModel(
            name='StatusMemberAnnualParticipation_save',
        ),
        migrations.DeleteModel(
            name='TotauxView_save',
        ),
        migrations.AlterField(
            model_name='adddepenses',
            name='date_depense',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cotisationoccasionnelle',
            name='date_cotisation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dons',
            name='date_don',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='editorialcommunity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='participationannual',
            name='date_participation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
