# Generated by Django 5.2.1 on 2025-06-21 00:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0002_alter_btestcustomuser_email_verification_expiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('montant_don', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif_don', models.TextField()),
                ('date_don', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='participationannual',
            old_name='participant',
            new_name='participant_id',
        ),
        migrations.AlterField(
            model_name='btestcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 22, 0, 57, 35, 862713, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='ParticipationOccasionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_participation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif_participation', models.TextField()),
                ('date_participation', models.DateField(auto_now_add=True)),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
