# Generated by Django 5.2.1 on 2025-07-02 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0003_dons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddDepenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=60)),
                ('montant_depense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif_depense', models.TextField()),
                ('date_depense', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='btestcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 3, 2, 38, 14, 696214, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='dons',
            name='date_don',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='participationannual',
            name='date_participation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='participationoccasionnelle',
            name='date_participation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
