# Generated by Django 5.2.1 on 2025-07-04 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0004_adddepenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btestcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 5, 2, 35, 43, 399455, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
