# Generated by Django 5.2.1 on 2025-07-08 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0005_alter_btestcustomuser_email_verification_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btestcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 9, 23, 59, 48, 292459, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='btestcustomuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('MODERATOR', 'Modérateur'), ('EDITOR', 'Éditeur'), ('USER', 'Utilisateur normal'), ('SECRETOR', 'Gestionnaire des cotisations'), ('SECOND_SECRETOR', 'Gestionnaire des dépenses')], default='USER', max_length=20),
        ),
    ]
