# Generated by Django 5.2.1 on 2025-07-10 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0007_alter_btestcustomuser_email_verification_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btestcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 11, 0, 41, 34, 608417, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='editorialcommunity',
            name='author',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='editorialcommunity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/missidhe_bourou_img'),
        ),
    ]
