# Generated by Django 5.2.1 on 2025-07-12 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0009_alter_btestcustomuser_email_verification_expiration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editorialcommunity',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='adddepenses',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='dons',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='editorialcommunity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='participationannual',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='participationoccasionnelle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='btestcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 13, 1, 31, 3, 762203, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
