# Generated by Django 5.2.1 on 2025-07-15 02:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0010_rename_date_created_editorialcommunity_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='btestcustomuser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='btestcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 16, 2, 42, 53, 655076, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
