# Generated by Django 5.2.1 on 2025-07-18 00:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0011_btestcustomuser_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dons',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_dons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participationannual',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_participation_annuel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participationoccasionnelle',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_participation_occasionnelle', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='btestcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 19, 0, 31, 48, 861466, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
