# Generated by Django 5.2.1 on 2025-07-18 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0013_applique_to_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btestcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 19, 0, 35, 34, 651244, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
