# Generated by Django 5.2.1 on 2025-07-21 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0014_alter_btestcustomuser_email_verification_expiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('url_name', models.CharField(max_length=100)),
                ('required_role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('MODERATOR', 'Modérateur'), ('EDITOR', 'Éditeur'), ('USER', 'Utilisateur normal'), ('SECRETOR', 'Gestionnaire des cotisations'), ('SECOND_SECRETOR', 'Gestionnaire des dépenses')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='btestcustomuser',
            options={'permissions': [('manager_adminstrators', 'Can manage administrators'), ('manage_users', 'Can manage users'), ('manage_articles', 'Can manage articles'), ('manager_cotisations', 'Can manage cotisations'), ('manager_depenses', 'Can manage depenses')]},
        ),
        migrations.AlterField(
            model_name='btestcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 22, 1, 19, 26, 174724, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
