# Generated by Django 5.2.1 on 2025-07-21 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0015_dashboardmodule_alter_btestcustomuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='btestcustomuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pictures'),
        ),
        migrations.AlterField(
            model_name='btestcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 22, 2, 33, 38, 470655, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
