# Generated by Django 5.2.1 on 2025-07-29 01:04

import Bapp.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0016_btestcustomuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btestcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 30, 1, 4, 46, 901566, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='btestcustomuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=Bapp.models.get_profile_image_path),
        ),
        migrations.CreateModel(
            name='PDFManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('file', models.FileField(upload_to='pdfs/%Y/%m/%d/', verbose_name='Fichier PDF')),
                ('document_type', models.CharField(choices=[('USER_LIST', 'Liste des utilisateurs'), ('ANNUAL_COTISATION', 'Cotisation annuelle'), ('OCCASIONNAL_COTISATION', 'Cotisation occasionnelle'), ('DONS', 'Rapport des ventes'), ('DEPENSES', 'Dépenses effectuées'), ('BILAN_CAISSE', 'Bilan financier')], max_length=100, verbose_name='Type de document')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_pdfs', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'PDF généré',
                'verbose_name_plural': 'PDFs générés',
                'ordering': ['-created_at'],
            },
        ),
    ]
