# Generated by Django 5.2.1 on 2025-07-29 23:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0018_convert_manger_name_to_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddepenses',
            name='manager_name',
            field=models.CharField(blank=True, default='default', max_length=60),
        ),
        migrations.AlterField(
            model_name='adddepenses',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='btestcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 30, 23, 56, 14, 970439, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
