# Generated by Django 5.2.1 on 2025-07-30 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0019_adddepenses_manager_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddepenses',
            name='manager_name',
        ),
        migrations.AlterField(
            model_name='btestcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 31, 0, 2, 36, 211736, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
