# Generated by Django 5.2.1 on 2025-08-18 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0020_remove_adddepenses_manager_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btestcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 19, 1, 23, 31, 549055, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='pdfmanager',
            name='document_type',
            field=models.CharField(choices=[('USER_LIST', 'Liste des utilisateurs'), ('ANNUAL_COTISATION', 'Cotisation annuelle'), ('OCCASIONNAL_COTISATION', 'Cotisation occasionnelle'), ('DONS', 'Rapport des ventes'), ('DEPENSES', 'Dépenses effectuées'), ('BILAN_CAISSE', 'Bilan financier'), ('INFO', 'Annonces ')], max_length=100, verbose_name='Type de document'),
        ),
    ]
