# Generated by Django 5.2.1 on 2025-08-18 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0022_alter_btestcustomuser_email_verification_expiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissidehBourouMembersView',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'missideh_bourou_members_view',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='btestcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 19, 1, 31, 41, 895082, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
