# Generated by Django 5.2.1 on 2025-08-18 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0023_missidehbouroumembersview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btestcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 19, 1, 34, 38, 105967, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
