# Generated by Django 5.2.1 on 2025-08-18 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0026_alter_btestcustomuser_email_verification_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btestcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 19, 22, 20, 26, 904003, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
