# Generated by Django 5.2.1 on 2025-08-26 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0028_alter_btestcustomuser_email_verification_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='btestcustomuser',
            name='otp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='btestcustomuser',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='btestcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 27, 1, 39, 28, 33367, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='twofactorauth',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
