# Generated by Django 5.2.1 on 2025-08-28 01:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0029_btestcustomuser_otp_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btestcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 29, 1, 39, 54, 783105, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='twofactorauth',
            name='channel',
            field=models.CharField(choices=[('email', 'email'), ('whatsapp', 'whatsapp'), ('telegram', 'telegram')], default='email', max_length=20),
        ),
        migrations.CreateModel(
            name='TwoFactorSettingsTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('telegram_linked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twofa_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
