# Generated by Django 5.2.1 on 2025-09-06 03:39

import Bapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0031_alter_btestcustomuser_email_verification_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participationannual',
            name='year',
            field=models.PositiveIntegerField(default=Bapp.models.current_year),
        ),
        migrations.AddField(
            model_name='participationoccasionnelle',
            name='year',
            field=models.PositiveIntegerField(default=Bapp.models.current_year),
        ),
        migrations.AlterField(
            model_name='btestcustomuser',
            name='email_verification_expiration',
            field=models.DateTimeField(blank=True, default=Bapp.models.default_email_verification_expiration, null=True),
        ),
    ]
