# Generated by Django 5.2.1 on 2025-09-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0032_participationannual_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotisationAnnuelleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_cotisation', models.DateTimeField()),
            ],
            options={
                'db_table': 'cotisation_annuelle_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CotisationOccasionnelleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif_cotisation', models.TextField()),
                ('date_cotisation', models.DateTimeField()),
            ],
            options={
                'db_table': 'cotisation_occasionnelle_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DepensesView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif_depense', models.TextField()),
                ('date_depense', models.DateTimeField()),
            ],
            options={
                'db_table': 'depenses_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DonsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif_don', models.TextField()),
                ('date_don', models.DateTimeField()),
            ],
            options={
                'db_table': 'dons_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TotauxView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_cotisationannuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_cotisationoccasionnelle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_dons', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_depenses', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'totaux_view',
                'managed': False,
            },
        ),
    ]
