# Generated by Django 5.2.1 on 2025-09-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0033_cotisationannuelleview_cotisationoccasionnelleview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusMemberAnnualParticipation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('prenoms', models.TextField()),
                ('quartier', models.TextField()),
                ('statut_par_annee', models.JSONField()),
            ],
            options={
                'verbose_name': 'Participation annuelle (vue)',
                'verbose_name_plural': 'Participations annuelles (vue)',
                'db_table': 'status_member_annual_participation',
                'managed': False,
            },
        ),
    ]
