# Generated by Django 5.2.1 on 2025-09-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0034_statusmemberannualparticipation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnoncesMembersView',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/missidhe_bourou_img')),
                ('extra_links', models.URLField(blank=True, null=True)),
                ('published_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'annonces_members_view',
                'managed': False,
            },
        ),
    ]
