# Generated by Django 5.2.1 on 2025-11-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0035_annoncesmembersview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btestcustomuser',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='btestcustomuser',
            name='prenoms',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='btestcustomuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('PRESIDENT', 'Président'), ('VICE_PRESIDENT', 'Vice-président'), ('PORTE_PAROLE', 'Porte-parole'), ('MODERATOR', 'Modérateur'), ('EDITOR', 'Éditeur'), ('USER', 'Membre'), ('SECRETOR', 'Sécréteur'), ('SECOND_SECRETOR', 'Second sécréteur')], default='USER', max_length=20),
        ),
        migrations.AlterField(
            model_name='dashboardmodule',
            name='required_role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('PRESIDENT', 'Président'), ('VICE_PRESIDENT', 'Vice-président'), ('PORTE_PAROLE', 'Porte-parole'), ('MODERATOR', 'Modérateur'), ('EDITOR', 'Éditeur'), ('USER', 'Membre'), ('SECRETOR', 'Sécréteur'), ('SECOND_SECRETOR', 'Second sécréteur')], max_length=20),
        ),
    ]
