# Generated by Django 5.2.1 on 2025-11-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bapp', '0036_alter_btestcustomuser_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='btestcustomuser',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
