"""
Django settings for BTest project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import base64
import os
from ast import literal_eval
from pathlib import Path

from django.conf.global_settings import SECRET_KEY, DEBUG
from dotenv import load_dotenv

from Bapp.middlewars import MediaDebugMiddleware

#importation du module decouple pour pouvoir integrer le fichier .aappgenv
from decouple import Config, RepositoryEnv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
#On charge le fichier qui gére les donnés de connxion à l'email
#config = Config(RepositoryEnv(BASE_DIR / '.mail_login_env'))
load_dotenv(BASE_DIR / '.mail_login_env')
load_dotenv(BASE_DIR / '.login_env')


SECRET_KEY = os.getenv('SECRET_KEY')

# Configuration du DEBUG
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

# Configuration des ALLOWED_HOSTS
#if DEBUG:
#    ALLOWED_HOSTS = ['*']
#    print(DEBUG, SECRET_KEY)
#else:
#    # Valeur par défaut sécurisée
#    default_hosts = 'http://localhost, http://127.0.0.1, http://bourou_test.local'
#    ALLOWED_HOSTS = [
#        host.strip()
#        for host in os.getenv('ALLOWED_HOSTS', default_hosts).split(',')
#        if host.strip()
#    ]
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '192.168.1.109', 'bourou_test.local', '0d30d6ed9c89.ngrok-free.app']

print(ALLOWED_HOSTS)
#CSRF_TRUSTED_ORIGINS = ALLOWED_HOSTS
#Database login
DB_NAME = os.getenv('DB_NAME')
PG_ADMIN_USER = os.getenv('PG_ADMIN_USER')
PG_PASSWORD_PASSWORD = os.getenv('PG_ADMIN_PASSWORD')
PG_HOST = os.getenv('PG_HOST', 'db')
PG_PORT = os.getenv('PG_PORT', '5432')

print(DB_NAME, PG_ADMIN_USER, PG_PASSWORD_PASSWORD, PG_HOST, PG_PORT, SECRET_KEY, DEBUG, ALLOWED_HOSTS, sep='\n')
#Email login

#Systéme de gestion de mails
#EMAIL_HOST = os.getenv('EMAIL_HOST')
#EMAIL_PORT = os.getenv('EMAIL_PORT', default=25)
#EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', default='')
#EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', default='')
#EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', default=True).lower() == 'true'
#EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', default=False).lower() == 'true'

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
    CSRF_TRUSTED_ORIGINS = [
        'https://*.ngrok.io',
        'https://*.ngrok-free.app',
    ]

EMAIL_HOST='smtp.ionos.de'
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_USE_SS=False
EMAIL_HOST_USER='m-cherif@leyssare.net'
EMAIL_HOST_PASSWORD='eXF18Rpngtdw'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_pgviews',
    'rest_framework',
    'corsheaders',
    'Bapp',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'Bapp.middlewars.MediaDebugMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

]

AUTH_USER_MODEL = 'Bapp.BTestCustomUser'
ROOT_URLCONF = 'BTest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BTest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': DB_NAME,
        'USER': PG_ADMIN_USER,
        'PASSWORD': PG_PASSWORD_PASSWORD,
        'HOST': PG_HOST,
        'PORT': PG_PORT,
        'OPTIONS': {
            'connect_timeout': 5,
        },
        'TEST': {
            'NAME': DB_NAME,
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#Url de redireciton après authentification
LOGIN_REDIRECT_URL = 'Bapp:dashboard2'
LOGIN_URL = 'Bapp:manager_login_page'

#Personnalisation et activation de code d'erreurs
handler403 = 'Bapp.views.custom_permission_denied_view'
handler404 = 'Bapp.views.custom_page_not_found_view'
handler500 = 'Bapp.views.custom_server_error_view'

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


#Systéme de gestion des sessions django

SESSION_COOKIE_NAME = 'bapp_sessionid'
SESSION_COOKIE_AGE = 1000
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
#Pour prolonger le temps si l'utilisateur reste actif sur le site.
SESSION_SAVE_EVERY_REQUEST = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'Bapp/static'
# Répertoires où Django cherchera les fichiers statiques

# Configuration pour les PDFs
PDFS_ROOT = os.path.join(BASE_DIR, 'pdfs')
PDFS_URL = '/pdfs/'

# Créer le répertoire s'il n'existe pas
if not os.path.exists(PDFS_ROOT):
    os.makedirs(PDFS_ROOT)
print(PDFS_ROOT, PDFS_URL, sep='\n')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration de l'application pour l'utilisation de Telegram 2FA'
TELEGRAM_BOT_USERNAME = 'thiaghel_bot'
TELEGRAM_BOT_TOKEN = "7954170802:AAHh-TBDEKagGbxZLd_1sjyr93Sn9d8EW3M"
TELEGRAM_API = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}"
TELEGRAM_WEBHOOK_SECRET = 'mSuUShtYYR68MqR9dLsEfwYXJOO3X_eStdu78GhvLKkCA2dfTb7Vs9oPzBuz20kD'

