# Generated by Django 5.2.1 on 2025-09-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('fichier', models.ImageField(upload_to='images/originals/')),
                ('fichier_mobile', models.ImageField(blank=True, null=True, upload_to='images/mobile/')),
                ('fichier_thumbnail', models.ImageField(blank=True, null=True, upload_to='images/thumbnails/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
