# Generated by Django 5.2.1 on 2025-09-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caroussel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
